name: bedwarsPlugin
version: '${project.version}'
main: me.athreetoedsloth.bedwarsplugin.BedwarsPlugin

commands:
  start:
    description: Starts the game.
    usage: /<command>

  end:
    description: End the game.
    usage: /<command>
