name: bedwarsPlugin
version: '1'
main: me.athreetoedsloth.bedwarsplugin.BedwarsPlugin

commands:
  createteam:
    description: Creates a new team.
    usage: /<command> <color>

  start:
    description: Starts the game.
    usage: /<command>