name: bedwarsPlugin
version: '1'
main: me.athreetoedsloth.bedwarsplugin.BedwarsPlugin

commands:
  start:
    description: Starts the game.
    usage: /<command> <2-8>

  end:
    description: End the game.
    usage: /<command>

  setlobbyspawn:
    description: Sets the lobby's spawn point.
    usage: /<command>

  setteamspawn:
    description: Sets the spawn point for the teams.
    usage: /<command> <0-7>

  setbedspawn:
    description: Sets the spawn point for the beds.
    usage: /<command> <0-7>

  blockprotection:
    description: Toggle the block protection.
    usage: /<command>

